name: mytodo
description: "A new Flutter project."
publish_to: 'none' 

# ✅ Fix: Dart SDK Version Added
environment:
  sdk: ">=3.5.0 <4.0.0"

# ✅ Dependencies Section Fix
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.25.4  # ✅ Updated version
  firebase_auth: ^4.17.8  # ✅ Updated version
  cloud_firestore: ^4.15.8  # ✅ Updated version
  firebase_storage: ^11.6.8  # ✅ Updated version
  fluttertoast: ^8.2.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
